### ISSUE TITLE
.png file now can be deleted

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_fontawesome#11]
it's black, not ok for white icons.

**Comment by TomBraider42** [comment]
No, i use black icons.
The local icon will not be used until it will be copied to sideicons\...
For usibility we should provide light and dark icons.

**Comment by TomBraider42** [comment]
![fontawesome_white](https://user-images.githubusercontent.com/5128016/37700202-e558d46e-2cea-11e8-8e70-689671fcae45.png)
![fontawesome_black](https://user-images.githubusercontent.com/5128016/37700203-e5719378-2cea-11e8-8ddf-6db7d66e1090.png)

**Comment by TomBraider42** [comment]
`app_proc(PROC_SIDEPANEL_ADD_DIALOG, (self.title, id_dlg, os.path.join(dir, 'fontawesome.png')))`
Do we need the icon path in this line? It will not be used?

**Comment by Alexey-T** [comment]
If path missed then dir sideicons is used... to use plugin dir- you need path..

**Comment by TomBraider42** [comment]
To understand...
With sidebar themes i can't provide the correct icon because i don't know the user needs the light or dark version.
So i add both icons (fontawesome_white.png, fontawesome_black.png) to plugin dir an the user have to copy the icon to the theme dir.
In install.inf: `icon=fontawesome_white.png`
Maybe we need an fallback icon (and a hint what to do) if the path in install.inf wasn't found.
Or if icon wasn't found in theme dir, CudaText looks at plugin dir. Then the user only have to change the name in install.inf if he needs the other icon.

The path in
`app_proc(PROC_SIDEPANEL_ADD_DIALOG, (self.title, id_dlg, os.path.join(dir, 'fontawesome_black.png')))`
will completely ignored, even if its an correct path.
So we can use
`app_proc(PROC_SIDEPANEL_ADD_DIALOG, (self.title, id_dlg))`

**Comment by Alexey-T** [comment]
IMHO best to do - make two icons. In plugin dir. in Inf write line as 

icon={dir}/fontawesome_white.png

With macro.

**Comment by TomBraider42** [comment]
With {dir} is plugin dir? Sounds good.

**Comment by Alexey-T** [comment]
It is documented macro in Cud wiki

**Comment by TomBraider42** [comment]
Ok, got it. Works fine!
